# Generated by Django 5.2 on 2025-05-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0004_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='first_name',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='height',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='last_name',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='weight',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
