# Generated by Django 5.2 on 2025-05-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0005_alter_healthprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='height',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='weight',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
